
# Git 관리 제외 대상 (로컬 전용)
jwt:
  secret: ${ADMIN_SECRET_TOKEN:default-secret-NBE9-11-2-Team01-project-key-for-jwt-token-2026}
  # secret: "prgrms-be-devcourse.NBE9-11-2-Team01-project-key-for-jwt-token-2026"
# 운영 환경 배포 시 실제 SMTP 정보를 입력하거나 환경변수로 대체하십시오.

spring:
  config:
    activate:
      on-profile: local
  
  # GreenMail 가상 서버용 설정 (로컬 테스트 시 활성화)
  mail:
    host: localhost
    port: 3025
    username: user
    password: password
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  # 외부 API 연동 시 아래 주석 해제 (실제 운영 환경 예시)
  # mail:
  #   host: smtp.sendgrid.net
  #   port: 587
  #   username: apikey
  #   password: SG.your_generated_api_key_here
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

  data:
    redis:
      host: localhost
      port: 6379
