# 메인 설정 파일
spring:
  # 1. 설정 임포트 (외부 설정 파일 불러오기)
  config:
    import:
      - optional:classpath:application-secret.yaml
      - optional:classpath:application-mail.yaml

  # 2. 이메일 발송용 설정


# 4. 기타 설정 (spring 블록 밖)
custom:
  cookie:
    secure: ${COOKIE_SECURE:true} # 환경 변수가 없으면 기본값 true