spring:
  application:
    name: backend
  jpa:
    hibernate:
      naming:
        # 엔티티 필드명 그대로 DB 컬럼명(카멜케이스, 언더스코어 변환 없음)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

<<<<<<< HEAD
# [신규 추가] JWT 보안 설정을 위한 비밀키
jwt:
  secret: "human-evolution-project-secret-key-for-jwt-token-2026"
=======

# [신규 추가] JWT 보안 설정을 위한 비밀키
jwt:
  secret: human-evolution-project-secret-key-for-jwt-token-2026
>>>>>>> b626abed2fefd6c3fbb9ddd0f5e3cdb84db7645c
